package org.brutality.model.content.achievement;
/**
 * 
 * @author Jason http://www.rune-server.org/members/jason
 * @date Mar 27, 2014
 */
public enum AchievementType {
	
	KILL_ROCK_CRAB, KILL_CHAOS_DRUID, JOIN_GUILD, WAR_ENLISTMENT, KILL_GUILD_PLAYER,
	WIN_GUILD_WAR, VOTE, PLAY_TIME, KILL_PLAYER, PLAYER_KILLSTREAK,
	RUNECRAFTING, HERBLORE, THIEVING, CRAFTING, SLAYER, SMELTING, AGILITY, KARAMBWAN, SUPER_COMBAT,
	MINING, FISHING, COOKING, FIREMAKING, WOODCUTTING, FARMING, BONE_ON_ALTAR, JAD, BARROWS,
	EAT_FOOD, DRINK_POTION, COMBAT_LEVEL, BARROWS_BROTHERS, PEST_CONTROL, DRAGON_DEN, CASKET,
	TZ_TOK_JAD, ALCHEMY, TOTAL_LEVEL, FINISH_SLAYER_TASK, GENIE_EVENT, LEARNING_THE_ROPES, 
	READ_RULES, SKILLCAPE_ANIMATION, TELEPORTING, COMPLETE_DUNG_FLOOR, WEAR_DBOW,
	WEAR_WHIP, RARE_DROP, KILL_GREEN_DRAGON, KILL_YAK, KILL_BANSHEE, KILL_BASILISK,
	KILL_INFERNAL_MAGE, KILL_BLOODVELD, KILL_TUROTH, KILL_JELLY, KILL_CAVE_HORROR, 
	KILL_DUST_DEVIL, KILL_KURASK, KILL_AQUANITE, KILL_NECHRYAEL,
	KILL_GARGOYLE, KILL_ABYSSAL_DEMON, KILL_BLUE_DRAGON, KILL_BRONZE_DRAGON,
	KILL_IRON_DRAGON, KILL_STEEL_DRAGON, KILL_BLACK_DEMON, KILL_HELLHOUND, KILL_DRAGON, KILL_BABY_DRAGON,
	KILL_NPC, KILL_COCKROACH_SOLDIER, KILL_DAGANNOTH, MINE_RUNE, MINE_ADAMANTITE, MINE_MITHRIL,
	FISH_ROCKTAIL, FISH_MANTA, FISH_SHARK, COOK_ROCKTAIL, COOK_SHARK, COOK_MANTA, KILL_BOSS, COMPLETE_BOSS_TASK

}
